name: APK Derleme Otomasyonu (Kivy Docker)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repositori Kodlarını Çek
      uses: actions/checkout@v4

    - name: Buildozer Action ile APK Derle
      uses: ArtemisS3/action-kivy-buildozer@v1
      with:
        workdir: .
        buildozer_version: 'stable'

    - name: Derlenen APK Dosyasını Yükle
      uses: actions/upload-artifact@v4
      with:
        name: AskUyumu-Debug-APK
        path: bin/*.apk
